export const CARDS = [
  {
    id: 1,
    '': 1,
    name: '명지횟집',
    type: 'MEAL',
    description:
      '명지횟집"은 부산광역시 강서구에 있습니다. 지방자치단체 인증을 받은 농림축산식품부 제공 안심식당입니다.',
    address: '부산광역시 강서구 신포길17번길 10-1',
    estimated_hours: 1,
    cost: 9100,
    rank: 0,
  },
  {
    id: 2,
    '': 1,
    name: '용두산식당',
    type: 'MEAL',
    description:
      '부산광역시 중구에서 맛집을 찾으신다면 "용두산식당"을 추천합니다.',
    address: '부산광역시 중구 대청로126번길 32-6',
    estimated_hours: 1,
    cost: 18800,
    rank: 1,
  },
  {
    id: 3,
    '': 1,
    name: '섹션',
    type: 'MEAL',
    description:
      '부산광역시 사상구에서 어디를 갈지 고민이라면! "섹션"에 가보시는 건 어떨까요?',
    address: '부산광역시 사상구 사상로309번길 16',
    estimated_hours: 1,
    cost: 18000,
    rank: 1,
  },
  {
    id: 4,
    '': 1,
    name: '흥화반점',
    type: 'MEAL',
    description:
      '부산광역시 부산진구에서 맛집을 찾으신다면 "흥화반점"에 방문해보세요. 부전역 근처에 있습니다. 지방자치단체 인증을 받은 농림축산식품부 제공 안심식당입니다. 50년 이상의 전통을 자랑합니다.',
    address: '부산광역시 부산진구 서전로47번길 52-1',
    estimated_hours: 1,
    cost: 18000,
    rank: 1,
  },
  {
    id: 5,
    '': 1,
    name: '하동집',
    type: 'MEAL',
    description:
      '부산광역시 서구에서 식당을 찾으신다면? "하동집"을 방문해보세요! 50년 이상의 전통을 자랑합니다.',
    address: '부산광역시 서구 구덕로124번길 59-1',
    estimated_hours: 1,
    cost: 9400,
    rank: 0,
  },
  {
    id: 6,
    '': 1,
    name: '묘향정',
    type: 'MEAL',
    description:
      '부산광역시 영도구에서 가 볼 만한 식당을 찾으신다면? "묘향정"을 추천합니다! 50년 이상의 전통을 자랑합니다.',
    address: '부산광역시 영도구 청학로6번길 4',
    estimated_hours: 1,
    cost: 28200,
    rank: 2,
  },
  {
    id: 7,
    '': 1,
    name: '중화각',
    type: 'MEAL',
    description:
      '어디 가야 할지 고민이시라고요? 그럼 부산광역시 동구 맛집, "중화각"을 추천합니다! 50년 이상의 전통을 자랑합니다.',
    address: '부산광역시 동구 망양로689번길 10',
    estimated_hours: 1,
    cost: 19000,
    rank: 1,
  },
  {
    id: 8,
    '': 1,
    name: '밀양보신탕',
    type: 'MEAL',
    description:
      '무엇을 먹을지 고민되신다고요? 부산광역시 동구에 계시다면 "밀양보신탕"을 추천합니다! 50년 이상의 전통을 자랑합니다.',
    address: '부산광역시 동구 중앙대로361번길 36-3',
    estimated_hours: 1,
    cost: 9000,
    rank: 0,
  },
  {
    id: 9,
    '': 1,
    name: '덕화원',
    type: 'MEAL',
    description:
      '부산광역시 동구에 가신다면 "덕화원"에 방문해보세요~ 50년 이상의 전통을 자랑합니다.',
    address: '부산광역시 동구 진성로 8-1',
    estimated_hours: 1,
    cost: 9000,
    rank: 0,
  },
  {
    id: 10,
    '': 1,
    name: '동흥 중화요리',
    type: 'MEAL',
    description:
      '어디 가야 할지 고민이시라고요? 그럼 부산광역시 동구 맛집, "동흥 중화요리"를 추천합니다! 50년 이상의 전통을 자랑합니다.',
    address: '부산광역시 동구 중앙대로251번길 8-1',
    estimated_hours: 1,
    cost: 28200,
    rank: 2,
  },
  {
    id: 11,
    '': 1,
    name: '몽마르지',
    type: 'MEAL',
    description:
      '몽마르지"를 부산광역시 동구의 가 볼 만한 식당으로 추천합니다! 50년 이상의 전통을 자랑합니다.',
    address: '부산광역시 동구 고관로29번길 24',
    estimated_hours: 1,
    cost: 9300,
    rank: 0,
  },
  {
    id: 12,
    '': 1,
    name: '함응보쌈사계절냉면',
    type: 'MEAL',
    description:
      '부산광역시 영도구에서 가 볼 만한 식당을 찾으신다면? "함응보쌈사계절냉면"을 추천합니다! 지방자치단체 인증을 받은 농림축산식품부 제공 안심식당입니다. 50년 이상의 전통을 자랑합니다.',
    address: '부산광역시 영도구 남항로 42',
    estimated_hours: 1,
    cost: 27600,
    rank: 2,
  },
  {
    id: 13,
    '': 1,
    name: '하늘소호프',
    type: 'MEAL',
    description:
      '하늘소호프"를 부산광역시 영도구의 가 볼 만한 식당으로 추천합니다! 50년 이상의 전통을 자랑합니다.',
    address: '부산광역시 영도구 절영로14번길 10',
    estimated_hours: 1,
    cost: 18800,
    rank: 1,
  },
  {
    id: 14,
    '': 1,
    name: '만다린',
    type: 'MEAL',
    description:
      '만다린"을 부산광역시 영도구의 가 볼 만한 식당으로 추천합니다! 50년 이상의 전통을 자랑합니다.',
    address: '부산광역시 영도구 절영로14번길 18',
    estimated_hours: 1,
    cost: 27600,
    rank: 2,
  },
  {
    id: 15,
    '': 1,
    name: '해동반점',
    type: 'MEAL',
    description:
      '해동반점"은 부산광역시 영도구에 있습니다. 50년 이상의 전통을 자랑합니다.',
    address: '부산광역시 영도구 절영로 151',
    estimated_hours: 1,
    cost: 9300,
    rank: 0,
  },
  {
    id: 16,
    '': 1,
    name: '삼화반점',
    type: 'MEAL',
    description:
      '무엇을 먹을지 고민되신다고요? 부산광역시 사하구에 계시다면 "삼화반점"을 추천합니다! 50년 이상의 전통을 자랑합니다.',
    address: '부산광역시 사하구 원양로 407',
    estimated_hours: 1,
    cost: 9000,
    rank: 0,
  },
  {
    id: 17,
    '': 1,
    name: '한전구내식당',
    type: 'MEAL',
    description:
      '부산광역시 서구에 가신다면 "한전구내식당"에 방문해보세요~ 50년 이상의 전통을 자랑합니다.',
    address: '부산광역시 서구 까치고개로 252',
    estimated_hours: 1,
    cost: 18200,
    rank: 1,
  },
  {
    id: 18,
    '': 1,
    name: '원향재',
    type: 'MEAL',
    description:
      '부산광역시 동구에 가신다면 "원향재"에 방문해보세요~ 이 매장은 블루리본 서베이에서 리본 1개를 받은 식당으로, "시간을 내어 다시 방문하고 싶은 곳"이라 평가받았습니다. 50년 이상의 전통을 자랑합니다.',
    address: '부산광역시 동구 대영로243번길 60',
    estimated_hours: 1,
    cost: 9100,
    rank: 0,
  },
  {
    id: 19,
    '': 1,
    name: '서울집',
    type: 'MEAL',
    description:
      '2020년 10월 22일 KBS1 6시내고향 7140회에서 소개되었던 맛집, "서울집"입니다! 부산광역시 영도구 근처라면 방문해보세요. 50년 이상의 전통을 자랑합니다.',
    address: '부산광역시 영도구 태종로99번길 28',
    estimated_hours: 1,
    cost: 9500,
    rank: 0,
  },
  {
    id: 20,
    '': 1,
    name: '함안돼지국밥',
    type: 'MEAL',
    description:
      '부산광역시 북구에서 식당을 찾으신다면? "함안돼지국밥"을 방문해보세요! 50년 이상의 전통을 자랑합니다.',
    address: '부산광역시 북구 구포만세길 77',
    estimated_hours: 1,
    cost: 18000,
    rank: 1,
  },
  {
    id: 21,
    '': 1,
    name: '신발원',
    type: 'MEAL',
    description:
      '2017년 04월 11일 KBS2 2TV생생정보 304회, 2016년 08월 20일 SBS 백종원의3대천왕 51회, 2014년 12월 17일 KBS1 6시내고향 5664회, 2013년 03월 13일 KBS2 생생정보통 617회, SBS 백종원의 3대 천왕 23회 등 여러 방송에서 다룬 바로 그 곳! 부산광역시 동구 인기 맛집 "신발원"을 방문해보세요! 이 매장은 2021년에 블루리본 서베이에서 리본 1개를 받은 식당으로, "시간을 내어 다시 방문하고 싶은 곳"이라 평가받았습니다. 50년 이상의 전통을 자랑합니다.',
    address: '부산광역시 동구 대영로243번길 62',
    estimated_hours: 1,
    cost: 9500,
    rank: 0,
  },
  {
    id: 22,
    '': 1,
    name: '진주식당',
    type: 'MEAL',
    description:
      '부산광역시 영도구 근처로 갈 일정이 있으시다면, 맛집으로 소문난 "진주식당"을 꼭 방문해보세요. 2020년 07월 24일 TV조선 식객허영만의백반기행 61회에 방영되었답니다. 50년 이상의 전통을 자랑합니다.',
    address: '부산광역시 영도구 절영로14번길 2',
    estimated_hours: 1,
    cost: 28200,
    rank: 2,
  },
  {
    id: 23,
    '': 1,
    name: '토종돼지국밥',
    type: 'MEAL',
    description:
      '토종돼지국밥"은 부산광역시 영도구에 있습니다. 50년 이상의 전통을 자랑합니다.',
    address: '부산광역시 영도구 남항남로9번길 14-2',
    estimated_hours: 1,
    cost: 9200,
    rank: 0,
  },
  {
    id: 24,
    '': 1,
    name: '어우량',
    type: 'MEAL',
    description:
      '어디 가야 할지 고민이시라고요? 그럼 부산광역시 영도구 맛집, "어우량"을 추천합니다! 50년 이상의 전통을 자랑합니다.',
    address: '부산광역시 영도구 태종로73번길 22',
    estimated_hours: 1,
    cost: 18000,
    rank: 1,
  },
  {
    id: 25,
    '': 1,
    name: '감천문화마을',
    type: 'ATTRACTION',
    description:
      "감천문화마을은 1950년대 한국전쟁 피난민의 삶의 터전으로 처음 자리 잡았어요. 산자락을 따라 질서정연하게 자리 잡은 계단식 집단 주거 형태와 모든 길이 서로 통하는 '미로미로' 골목길의 벽화들 그리고 파란 지붕이 감천문화마을의 상징이죠. 한국 현대사의 단면과 부산의 역사를 보여주는 감천문화마을의 특색과 역사적 가치를 살리기 위해 지역 예술인들과 마을 주민들이 모여 '마을미술 프로젝트'를 시작하였고, 현재 부산을 찾는 많은 사람이 꼭 방문하는 명소가 되었습니다.",
    address: '부산광역시 사하구 감내2로 203 감천문화마을안내센터',
    estimated_hours: 1,
    cost: 0,
    rank: 0,
  },
  {
    id: 26,
    '': 1,
    name: '해운대 해변',
    type: 'ATTRACTION',
    description:
      '해운대 해변은 부산을 대표하는 2대 해변 중 하나로, 수심이 얕고 조수의 변화가 심하지 않아 해수욕을 즐기기 안성맞춤인 장소에요. 해운대 바다가 보이는 호텔 안의 레스토랑이나 실내 풀장도 언제나 인기 만점이지요. 요트를 빌려서 해상 스포츠를 즐길 수도 있죠. 해운대 해수욕장 주변에는 훌륭한 펍과 음식점들이 가득해요. 부산의 명물 음식이든, 즐거운 클럽이든 이곳이라면 모두 찾으실 수 있을 거예요.',
    address: '부산광역시 해운대구 우동',
    estimated_hours: 2,
    cost: 0,
    rank: 0,
  },
  {
    id: 27,
    '': 1,
    name: '용두산공원',
    type: 'ATTRACTION',
    description:
      '용두산은 부산 3대 명산 중 하나로, 산의 모양이 마치 용을 닮았다 하여 용두산이라는 이름이 붙여졌지요. 한국전쟁 이후 피난민이 모여 산꼭대기까지 판잣집을 지었으나 화재로 다 타버린 아픈 역사가 있지만, 그 후 많은 사람의 노력으로 아름다운 공원으로 탈바꿈했지요. 명칭은 산이지만 최고 높이가 49m밖에 안 되는 한적한 언덕 공원이에요. 생각보다 긴 에스컬레이터나 계단을 이용해서 산책하는 기분으로 가볍게 올라갈 수 있습니다. 부산항이나 영도를 바라볼 수 있고, 부산타워 아래로는 우뚝 선 이순신 장군 동상이 보입니다.',
    address: '부산광역시 중구 용두산길 37-55',
    estimated_hours: 1,
    cost: 0,
    rank: 0,
  },
  {
    id: 28,
    '': 1,
    name: '범어사',
    type: 'ATTRACTION',
    description:
      '범어사는 신라 문무왕 18년(678년) 건립된 사찰로, 한국의 보물인 대웅전과 3층 석탑, 조계문 등으로 문화재로서의 가치가 풍부한 곳이에요. 또한, 아름다운 대나무숲과 어우러지는 한국 특유의 전통 건축양식이 특별함을 더해주죠. 범어사는 임진왜란 당시 호국불교의 중심지로 승병 활동을 하거나 일제강점기에 이곳에서 공부하던 학생들이 독립운동을 시작한 것으로 유명해졌어요. 종교적 시설일 뿐만 아니라 나라를 지키고자 하는 사상이 계승된 아주 특별한 사찰이죠. 우리 민족이 피워낸 문화와 쌀 한 톨, 한 방울의 물에서 지혜를 찾은 깨달음의 이야기를 들을 수 있는 곳입니다.',
    address: '부산광역시 금정구 범어사로 250 범어사',
    estimated_hours: 2,
    cost: 0,
    rank: 0,
  },
  {
    id: 29,
    '': 1,
    name: '태종대 공원',
    type: 'ATTRACTION',
    description:
      '태종대 공원에는 해발 250m의 최고봉을 중심으로 해송을 비롯한 120여 종의 수목이 울창하게 우거져 있어요. 백악기 말에 호수에 쌓인 퇴적층이 해수면 상승으로 파도에 의해 침식되어 만들어진 파식 대지, 해식애, 해안동굴 등의 암벽해안이 장관을 이룹니다. 탁 트인 대한 해협이 한눈에 들어오고 맑은 날에는 약 56㎞ 떨어진 일본의 쓰시마섬까지 볼 수 있어서 많은 국내외 관광객의 발길이 끊이지 않습니다. 이곳은 일본 강점기 때부터 오랫동안 군 요새로 사용되다가 1967년에 관광지로 지정되어 일반에 공개되었습니다. 2013년에는 국가 지질공원으로 인정되었죠.',
    address: '부산광역시 영도구 전망로 120',
    estimated_hours: 1,
    cost: 0,
    rank: 0,
  },
  {
    id: 30,
    '': 1,
    name: '자갈치시장',
    type: 'ATTRACTION',
    description:
      '부산 자갈치시장은 부산을 대표하는 전통 어시장이에요. 부산의 관광 명소 중 하나이며, 회를 비롯한 다양한 해산물을 만날 수 있어요. 자갈치라는 지명은 자갈 해안에서 비롯되었다는 설과 "자갈치"란 어종의 명칭에서 유래되었다는 설이 있지요. 새벽 바다를 가르며 어선이 들어오면 싱싱한 해산물을 내려놓는데, 곧 왁자지껄한 경매가 열리며 상인들이 그날 필요한 어패류를 구매해 수조를 채우죠. 어패류를 구매하여 집에 가고자 하는 손님들, 그리고 구매한 해산물을 즉석에서 회나 요리로 즐기려는 손님들로 시장은 언제나 분주해요. 또한, 자갈치 해안가 도로변에서는 "판매기 장수 아주머니"들이 고등어, 멍게, 고래고기 등을 파는 진귀한 모습을 볼 수 있어요.',
    address: '부산 중구 자갈치해안로 52 자갈치시장',
    estimated_hours: 1,
    cost: 0,
    rank: 0,
  },
  {
    id: 31,
    '': 1,
    name: '해동용궁사',
    type: 'ATTRACTION',
    description:
      "해동용궁사는 고려 우왕 2년(1376년) 건립된 아주 특별한 점이 많은 사찰이에요. 그중 단연 눈에 띄는 점은 검푸른 바닷물이 바로 발아래서 철썩대는 '수상법당'이라는 점이겠죠? 해동용궁사에서 바라보는 일출과 안개 낀 풍경, 바위에 부딪히는 파도 소리는 아름답기 그지없다고 합니다. 이런 해동용궁사는 또한 '소원을 들어주는 사찰'로 많은 관광객을 맞이하고 있어요. 자손이 없는 사람이 마음을 다해 기도하면 자손을 얻게 한다는 미륵 좌상이 있고, 계단 초입의 달마상의 코와 배를 만지면 득남한다는 전설이 전해 내려와요. 바라는 소원이 있다면 부산을 방문할 때 해동용궁사를 들러 보는 것도 좋을 거예요.",
    address: '부산광역시 기장군 기장읍 용궁길 86 해동용궁사',
    estimated_hours: 2,
    cost: 0,
    rank: 0,
  },
  {
    id: 32,
    '': 1,
    name: '부산시립미술관',
    type: 'ATTRACTION',
    description:
      '부산시립미술관은 1998년 개관하였고, 파도 모습을 닮은 건물 외형을 통해 부산의 특성을 시각화하고 있어요. 부산에서 활동하는 미술가는 물론 국내외 저명 미술가들의 작품을 감상할 수 있는 공간이에요. 부산 시립미술관은 또한 현대미술의 세계적 거장인 이우환 작가의 상설 전시공간이 별관으로 건립되어 부산의 명소로 거듭나고 있습니다. 이우환 작가는 직접 이 별관의 입지 선정부터 건축 기본설계, 그리고 디자인을 한 것으로 알려져 있어요. 최근 BTS의 RM이 이우환 별관을 방문한 것이 밝혀지면서 관람객의 발길이 줄을 이었다고 하네요.',
    address: '부산광역시 해운대구 APEC로 58 부산시립미술관',
    estimated_hours: 1,
    cost: 0,
    rank: 0,
  },
  {
    id: 33,
    '': 1,
    name: '부산타워',
    type: 'ATTRACTION',
    description:
      '부산을 상징하는 부산타워는 용두산공원에 있어요. 탑 높이는 120m이며 송신 및 중계를 위한 용도인 철탑이 없는 순수한 전망 탑입니다. 꼭대기에 있는 전망대는 부산에서 멀지 않은 경주 불국사 다보탑 지붕 모양을 본떠 만들었다고 해요. 멀리서부터 잘 보이는 하얀 탑이 항구 도시라는 부산 이미지에도 잘 맞는 볼만한 명소죠. 부산 구도심의 중심에 있는 거대한 전망 탑이라서 정겨운 옛날 시가지 모습을 내려다볼 수 있지요.',
    address: '부산 중구 용두산길 37-30',
    estimated_hours: 1,
    cost: 0,
    rank: 0,
  },
  {
    id: 34,
    '': 1,
    name: '베스티호텔',
    type: 'STAY',
    description: '051-710-9700 https://bestiehotel.southkrhotel.com/',
    address: '부산광역시 강서구 미음산단로 17',
    estimated_hours: 0,
    cost: 122000,
    rank: 0,
  },
  {
    id: 35,
    '': 1,
    name: '대저캠핑장',
    type: 'STAY',
    description: '051-941-0957 https://www.daejeocamping.com/',
    address: '부산광역시 강서구',
    estimated_hours: 0,
    cost: 468000,
    rank: 2,
  },
  {
    id: 36,
    '': 1,
    name: '공항하숙',
    type: 'STAY',
    description: '051-831-0606 https://hotelairport.modoo.at/',
    address: '부산광역시 강서구 공항로811번길 60-20',
    estimated_hours: 0,
    cost: 220000,
    rank: 1,
  },
  {
    id: 37,
    '': 1,
    name: '에어포트호텔',
    type: 'STAY',
    description: 'https://chorongblue.modoo.at/',
    address: '부산광역시 강서구 유통단지1로65번길 15',
    estimated_hours: 0,
    cost: 483000,
    rank: 2,
  },
  {
    id: 38,
    '': 1,
    name: '초롱블루펜션',
    type: 'STAY',
    description: '051-941-3008 http://naver.me/FS6A3TSC',
    address: '부산광역시 강서구 가덕해안로1169번길 62-33',
    estimated_hours: 0,
    cost: 132000,
    rank: 0,
  },
  {
    id: 39,
    '': 1,
    name: '하늘과바다',
    type: 'STAY',
    description: '051-971-9348 http://naver.me/Gfa3k3QS',
    address: '부산광역시 강서구 가덕해안로1169번길 80',
    estimated_hours: 0,
    cost: 145000,
    rank: 0,
  },
  {
    id: 40,
    '': 1,
    name: '대항체험마을민박',
    type: 'STAY',
    description: '051-271-1511 http://naver.me/xkxaXJGc',
    address: '부산광역시 강서구 가덕해안로1207번길',
    estimated_hours: 0,
    cost: 208000,
    rank: 1,
  },
  {
    id: 41,
    '': 1,
    name: '섬마을장어구이펜션',
    type: 'STAY',
    description: '051-717-3872 https://mjmartin.modoo.at',
    address: '부산광역시 강서구 가덕해안로1208번길 45',
    estimated_hours: 0,
    cost: 138000,
    rank: 0,
  },
  {
    id: 42,
    '': 1,
    name: '대항펜션',
    type: 'STAY',
    description: '051-271-2237 http://naver.me/FjoKaQKy',
    address: '부산광역시 강서구 가덕해안로1212번길 36',
    estimated_hours: 0,
    cost: 309000,
    rank: 2,
  },
  {
    id: 43,
    '': 1,
    name: '대항민박',
    type: 'STAY',
    description: '051-271-3687 http://naver.me/FdswQbIc',
    address: '부산광역시 강서구 가덕해안로1212번길 20',
    estimated_hours: 0,
    cost: 315000,
    rank: 2,
  },
  {
    id: 44,
    '': 1,
    name: 'W모텔',
    type: 'STAY',
    description: '051-271-1907 http://naver.me/xGOrX7rT',
    address: '부산광역시 강서구 르노삼성대로 598',
    estimated_hours: 0,
    cost: 298000,
    rank: 1,
  },
  {
    id: 45,
    '': 1,
    name: '비엠텔모텔',
    type: 'STAY',
    description: '051-271-0467 https://hotelheritage.modoo.at',
    address: '부산광역시 강서구 르노삼성대로 576-2',
    estimated_hours: 0,
    cost: 303000,
    rank: 2,
  },
  {
    id: 46,
    '': 1,
    name: '마틴호텔',
    type: 'STAY',
    description: '051-271-2001 https://designpop.modoo.at',
    address: '부산광역시 강서구 르노삼성대로 600',
    estimated_hours: 0,
    cost: 504000,
    rank: 2,
  },
  {
    id: 47,
    '': 1,
    name: 'JK호텔',
    type: 'STAY',
    description: '051-271-3125 http://naver.me/Gfa3keGi',
    address: '부산광역시 강서구 르노삼성대로 590',
    estimated_hours: 0,
    cost: 519000,
    rank: 2,
  },
  {
    id: 48,
    '': 1,
    name: '모텔 제타',
    type: 'STAY',
    description: '051-271-1511 http://naver.me/5lZGVMu7',
    address: '부산광역시 강서구 르노삼성대로 634',
    estimated_hours: 0,
    cost: 326000,
    rank: 1,
  },
  {
    id: 49,
    '': 1,
    name: '모텔 마르',
    type: 'STAY',
    description: '051-271-3777 https://browndot1.modoo.at',
    address: '부산광역시 강서구 르노삼성대로 634',
    estimated_hours: 0,
    cost: 105000,
    rank: 0,
  },
  {
    id: 50,
    '': 1,
    name: '헤리티지디자인호텔',
    type: 'STAY',
    description: 'http://naver.me/x6PtYui2',
    address: '부산광역시 강서구 르노삼성대로 592',
    estimated_hours: 0,
    cost: 138000,
    rank: 0,
  },
  {
    id: 51,
    '': 1,
    name: '디자인팝 모텔',
    type: 'STAY',
    description: '051-934-8600 http://naver.me/FcaXWW54',
    address: '부산광역시 강서구 르노삼성대로 576-4',
    estimated_hours: 0,
    cost: 390000,
    rank: 2,
  },
  {
    id: 52,
    '': 1,
    name: '씨사이드모텔',
    type: 'STAY',
    description: '051-911-5566 http://hotelou.kr',
    address: '부산광역시 강서구 르노삼성대로 566',
    estimated_hours: 0,
    cost: 330000,
    rank: 1,
  },
  {
    id: 53,
    '': 1,
    name: '비엠텔모텔',
    type: 'STAY',
    description: '051-207-1202 https://bsoiahotel.modoo.at',
    address: '부산광역시 강서구 르노삼성대로 576-2',
    estimated_hours: 0,
    cost: 320000,
    rank: 1,
  },
  {
    id: 54,
    '': 1,
    name: '브라운도트호텔 명지점',
    type: 'STAY',
    description: '051-271-8686 cohotel.modoo.at',
    address: '부산광역시 강서구 르노삼성대로 576-6',
    estimated_hours: 0,
    cost: 326000,
    rank: 1,
  },
  {
    id: 55,
    '': 1,
    name: '넘버25호텔',
    type: 'STAY',
    description: '051-661-9000 https://www.shillastay.com/',
    address: '부산광역시 강서구 명지국제2로28번길 7',
    estimated_hours: 0,
    cost: 537000,
    rank: 2,
  },
  {
    id: 56,
    '': 1,
    name: '더포인트호텔',
    type: 'STAY',
    description: '051-271-6566 http://naver.me/GLK4JPzg',
    address: '부산광역시 강서구 명지국제2로28번길 8',
    estimated_hours: 0,
    cost: 316000,
    rank: 1,
  },
  {
    id: 57,
    '': 1,
    name: '호텔오유',
    type: 'STAY',
    description: '051-271-0023 https://mjoceancity.modoo.at',
    address: '부산광역시 강서구 명지국제6로 21',
    estimated_hours: 0,
    cost: 230000,
    rank: 1,
  },
  {
    id: 58,
    '': 1,
    name: '오이아호텔명지',
    type: 'STAY',
    description: '051-271-4411 http://naver.me/5vILtjGn',
    address: '부산광역시 강서구 명지국제6로1번길 24',
    estimated_hours: 0,
    cost: 324000,
    rank: 2,
  },
  {
    id: 59,
    '': 1,
    name: '씨엘오션호텔',
    type: 'STAY',
    description: '051-271-2563 http://naver.me/xqfCdpFT',
    address: '부산광역시 강서구 명지국제6로34번길 22',
    estimated_hours: 0,
    cost: 141000,
    rank: 0,
  },
  {
    id: 60,
    '': 1,
    name: '신라스테이',
    type: 'STAY',
    description: '051-941-8688 http://instagram.com/legend_busan',
    address: '부산광역시 강서구 명지국제7로 38',
    estimated_hours: 0,
    cost: 136000,
    rank: 0,
  },
  {
    id: 61,
    '': 1,
    name: '넘버25호텔 명지오션시티점 비즈니스',
    type: 'STAY',
    description: '051-660-6901 http://www.bestlouishamilton.com',
    address: '부산광역시 강서구 명지오션시티3로 41',
    estimated_hours: 0,
    cost: 334000,
    rank: 1,
  },
  {
    id: 62,
    '': 1,
    name: '오션시티호텔',
    type: 'STAY',
    description: '051-832-0055 http://naver.me/FMANaTQT',
    address: '부산광역시 강서구 명지오션시티3로 37',
    estimated_hours: 0,
    cost: 282000,
    rank: 1,
  },
  {
    id: 63,
    '': 1,
    name: '사이버모텔',
    type: 'STAY',
    description: '051-831-9197 http://naver.me/5oQnCQ6U',
    address: '부산광역시 강서구 명지오션시티5로 18',
    estimated_hours: 0,
    cost: 537000,
    rank: 2,
  },
  {
    id: 64,
    '': 1,
    name: '호텔프렌치코드',
    type: 'STAY',
    description: '051-831-2460 http://naver.me/G7KpvCJu',
    address: '부산광역시 강서구 명지오션시티5로 8',
    estimated_hours: 0,
    cost: 135000,
    rank: 0,
  },
  {
    id: 65,
    '': 1,
    name: '레전드호텔',
    type: 'STAY',
    description: '051-831-2610 https://busanhotelthemay.modoo.at',
    address: '부산광역시 강서구 미음산단5로 48',
    estimated_hours: 0,
    cost: 240000,
    rank: 1,
  },
  {
    id: 66,
    '': 1,
    name: '베스트루이스해밀턴호텔 서부산점',
    type: 'STAY',
    description: '051-832-0128 http://s-motel.co.kr',
    address: '부산광역시 강서구 범방3로29번길 6',
    estimated_hours: 0,
    cost: 435000,
    rank: 2,
  },
  {
    id: 67,
    '': 1,
    name: '성고개산장',
    type: 'STAY',
    description: '051-831-9798 http://naver.me/5Q4m2LmH',
    address: '부산광역시 강서구 신촌소류지길 15-28',
    estimated_hours: 0,
    cost: 163000,
    rank: 0,
  },
  {
    id: 68,
    '': 1,
    name: '벨라지오모텔',
    type: 'STAY',
    description: '051-832-2223 http://www.hotel2gsn.com',
    address: '부산광역시 강서구 신호산단1로217번길 7',
    estimated_hours: 0,
    cost: 200000,
    rank: 1,
  },
  {
    id: 69,
    '': 1,
    name: 'IW모텔',
    type: 'STAY',
    description: '051-714-2556 https://browndotshinho.modoo.at',
    address: '부산광역시 강서구 신호산단1로217번길 19',
    estimated_hours: 0,
    cost: 123000,
    rank: 0,
  },
  {
    id: 70,
    '': 1,
    name: '호텔더메이',
    type: 'STAY',
    description: '051-271-7000 https://모두의주문.com/050353390688',
    address: '부산광역시 강서구 신호산단1로217번길 27',
    estimated_hours: 0,
    cost: 141000,
    rank: 0,
  },
  {
    id: 71,
    '': 1,
    name: '2월호텔',
    type: 'STAY',
    description: '051-831-5646 https://hoteltheone.modoo.at/?link=288ows6w',
    address: '부산광역시 강서구 신호산단1로217번길 31',
    estimated_hours: 0,
    cost: 142000,
    rank: 0,
  },
  {
    id: 72,
    '': 1,
    name: 'S모텔',
    type: 'STAY',
    description: '051-831-1105 http://naver.me/56I0AIDU',
    address: '부산광역시 강서구 신호산단1로217번길 37',
    estimated_hours: 0,
    cost: 156000,
    rank: 0,
  },
  {
    id: 73,
    '': 1,
    name: '블랑비즈니스호텔',
    type: 'STAY',
    description: '051-941-1929 http://naver.me/xuI5zfmT',
    address: '부산광역시 강서구 신호산단1로217번길 10',
    estimated_hours: 0,
    cost: 321000,
    rank: 2,
  },
  {
    id: 74,
    '': 1,
    name: '까르페호텔',
    type: 'STAY',
    description: 'http://naver.me/GmFiTAih',
    address: '부산광역시 강서구 신호산단1로217번길 15',
    estimated_hours: 0,
    cost: 507000,
    rank: 2,
  },
  {
    id: 75,
    '': 1,
    name: '호텔에그',
    type: 'STAY',
    description: '051-832-1117 http://naver.me/FCb2DiVn',
    address: '부산광역시 강서구 신호산단1로217번길 33',
    estimated_hours: 0,
    cost: 140000,
    rank: 0,
  },
  {
    id: 76,
    '': 1,
    name: '2월호텔 강서신관',
    type: 'STAY',
    description: '051-832-6660 https://goodprimehotel.modoo.at/',
    address: '부산광역시 강서구 신호산단1로217번길 12',
    estimated_hours: 0,
    cost: 140000,
    rank: 0,
  },
  {
    id: 77,
    '': 1,
    name: '브라운도트호텔',
    type: 'STAY',
    description: 'https://blog.naver.com/freedomapart',
    address: '부산광역시 강서구 신호산단1로72번길 33',
    estimated_hours: 0,
    cost: 294000,
    rank: 1,
  },
  {
    id: 78,
    '': 1,
    name: '더브레인호텔',
    type: 'STAY',
    description: 'http://www.xn--sk4bt1htzc9vo.kr/',
    address: '부산광역시 강서구 신호산단1로72번길 58',
    estimated_hours: 0,
    cost: 153000,
    rank: 0,
  },
  {
    id: 79,
    '': 1,
    name: '호텔더원',
    type: 'STAY',
    description: 'http://가덕도펜션.net',
    address: '부산광역시 강서구 신호산단1로72번길 41',
    estimated_hours: 0,
    cost: 312000,
    rank: 2,
  },
  {
    id: 80,
    '': 1,
    name: 'V호텔',
    type: 'STAY',
    description: 'http://010-2918-6536.1004114.co.kr',
    address: '부산광역시 강서구 신호산단2로27번길 33',
    estimated_hours: 0,
    cost: 270000,
    rank: 1,
  },
  {
    id: 81,
    '': 1,
    name: '비지니스호텔',
    type: 'STAY',
    description: 'http://holydream.co.kr/',
    address: '부산광역시 강서구 신호산단2로27번길 41',
    estimated_hours: 0,
    cost: 540000,
    rank: 2,
  },
  {
    id: 82,
    '': 1,
    name: '펀모텔',
    type: 'STAY',
    description: '070-4251-0481 http://xn--o39a22lsjo77b8qv.kr/',
    address: '부산광역시 강서구 신호산단2로27번길 27',
    estimated_hours: 0,
    cost: 127000,
    rank: 0,
  },
  {
    id: 83,
    '': 1,
    name: '이그니스호텔',
    type: 'STAY',
    description: 'http://naver.me/xJNodEsK',
    address: '부산광역시 강서구 신호산단2로27번길 21',
    estimated_hours: 0,
    cost: 352000,
    rank: 1,
  },
  {
    id: 84,
    '': 1,
    name: '굿프라임호텔',
    type: 'STAY',
    description: 'http://naver.me/x6PtYc48',
    address: '부산광역시 강서구 과학산단2로 12',
    estimated_hours: 0,
    cost: 336000,
    rank: 2,
  },
  {
    id: 85,
    '': 1,
    name: '헤르몬호텔',
    type: 'STAY',
    description: 'http://healingmb.com/',
    address: '부산광역시 강서구 과학산단2로10번길 23',
    estimated_hours: 0,
    cost: 492000,
    rank: 2,
  },
  {
    id: 86,
    '': 1,
    name: '카리브의일몰',
    type: 'STAY',
    description: '051-513-9100 http://naver.me/xXr6zXdc',
    address: '부산광역시 강서구 가덕해안로 712',
    estimated_hours: 0,
    cost: 450000,
    rank: 2,
  },
  {
    id: 87,
    '': 1,
    name: 'Tesla Model X',
    type: 'TRANSPORT',
    description: null,
    address: '',
    estimated_hours: 1,
    cost: 113490,
    rank: 1,
  },
  {
    id: 88,
    '': 1,
    name: 'Lamborghini Urus',
    type: 'TRANSPORT',
    description: null,
    address: '',
    estimated_hours: 1,
    cost: 697170,
    rank: 2,
  },
  {
    id: 89,
    '': 1,
    name: 'Kia Sportage',
    type: 'TRANSPORT',
    description: null,
    address: '',
    estimated_hours: 1,
    cost: 47960,
    rank: 0,
  },
  {
    id: 90,
    '': 1,
    name: 'BMW X5',
    type: 'TRANSPORT',
    description: null,
    address: '',
    estimated_hours: 1,
    cost: 116680,
    rank: 1,
  },
  {
    id: 91,
    '': 1,
    name: 'Rolls-Royce Cullinan',
    type: 'TRANSPORT',
    description: null,
    address: '',
    estimated_hours: 1,
    cost: 702170,
    rank: 2,
  },
  {
    id: 92,
    '': 1,
    name: '라이언 홀리데이 인 부산',
    type: 'ACTIVITY',
    description:
      '매우 귀여운 장소, 개인적으로 찾기가 조금 어렵다고 생각합니다. 주변에 테마 레스토랑이 많이 있으며 인터랙티브 경험을 할 수있는 공간이 있습니다. Ryan을 좋아한다면 방문 할 수 있습니다!',
    address: '부산광역시 해운대구 해운대해변로 292',
    estimated_hours: 2,
    cost: 20000,
    rank: 0,
  },
  {
    id: 93,
    '': 1,
    name: '롯데월드 어드벤처 부산',
    type: 'ACTIVITY',
    description:
      '부산 최대 규모의 테마파크, 마법과 환상의 세계로 여러분을 초대합니다! 신나고 즐거운 어트랙션으로 짜릿한 스릴감을 즐겨보세요. 눈길을 사로잡는 화려한 공연과 퍼레이드도 준비되어 있습니다.',
    address: '부산 기장군 기장읍 동부산관광로 42',
    estimated_hours: 5,
    cost: 42300,
    rank: 2,
  },
  {
    id: 94,
    '': 1,
    name: '부산 기장 스카이라인 루지',
    type: 'ACTIVITY',
    description:
      '멋진 부산 바다를 보며 루지를 타고 달려보세요! 스카이라이드와 함께 동부산의 빼어난 절경을 감상해보세요. 아름다운 바다를 배경으로 온 가족 모두가 시원하게 즐길 수 있어요.',
    address: '부산광역시 기장군 기장읍 기장해안로 205',
    estimated_hours: 2,
    cost: 30000,
    rank: 1,
  },
  {
    id: 95,
    '': 1,
    name: '부산 송도 해상케이블카',
    type: 'ACTIVITY',
    description:
      '최대 86m 상공을 가로지르며 부산의 전경을 파노라마로 즐길 수 있어요. 케이블카 이용 시 무료 주차가 가능해요. 가족들과의 즐거운 추억을 더욱 편하게 만들어 보세요. 바닥이 투명한 크리스탈 크루즈 케이블카로 짜릿함을 느껴볼 수 있어요.',
    address: '부산광역시 서구 송도해변로 171',
    estimated_hours: 1,
    cost: 16000,
    rank: 0,
  },
  {
    id: 96,
    '': 1,
    name: '광안리 서프마린 서핑&패들보드 체험',
    type: 'ACTIVITY',
    description:
      '부산 광안리 바다를 배경으로 패들보드를 타며 여유를 느껴보세요. 서프마린은 엄선된 전문 강사들로 이루어진 패들보드샵 이에요. 패들보드에 대한 열정이 가득한 서프마린과 열정으로 가득한 하루를 함께 하셔도 좋아요.',
    address: '부산시 수영구 광안해변로 125 우진빌딩 지하1층',
    estimated_hours: 2,
    cost: 35000,
    rank: 1,
  },
  {
    id: 97,
    '': 1,
    name: '부산야경 스냅투어',
    type: 'ACTIVITY',
    description:
      '호천마을, 황령산, 광안리 해수욕장 그리고 더베이 101을 당일에 전부 다녀올 수 있는 알찬 패키지 입니다. 핸드폰 촬영이 어려운 야경사진을 전문 카메라 장비와 여러가지 소품을 활용하여 아름다운 부산의 밤풍경을 배경으로 인생사진을 찍어드립니다. 매일 소규모로 진행이 되어 투어에 참여한 다른 여행객들과 화목한 분위기에서 투어가 진행되며, 새로운 사람들과 소통하고, 여행 친구도 사귈수 있는 투어입니다. 부산토박이의 전문 가이드가 알려주는 부산의 이야기를 통해 부산의 이모저모를 알아가실 수 있습니다.',
    address: '부산광역시 부산진구 엄광로 491',
    estimated_hours: 4,
    cost: 61900,
    rank: 2,
  },
  {
    id: 98,
    '': 1,
    name: 'Hyundai Avante',
    type: 'TRANSPORT',
    description: null,
    address: '',
    estimated_hours: 1,
    cost: '22,347',
    rank: 0,
  },
  {
    id: 99,
    '': 1,
    name: 'Hyundai Starex',
    type: 'TRANSPORT',
    description: null,
    address: '',
    estimated_hours: 1,
    cost: 23463,
    rank: 0,
  },
  {
    id: 100,
    '': 1,
    name: 'Kia Carnival',
    type: 'TRANSPORT',
    description: null,
    address: '',
    estimated_hours: 1,
    cost: 29259,
    rank: 0,
  },
  {
    id: 101,
    '': 1,
    name: 'KG Torres',
    type: 'TRANSPORT',
    description: null,
    address: '',
    estimated_hours: 1,
    cost: 33201,
    rank: 0,
  },
  {
    id: 102,
    '': 1,
    name: 'Hyundai Kona',
    type: 'TRANSPORT',
    description: null,
    address: '',
    estimated_hours: 1,
    cost: 31599,
    rank: 0,
  },
  {
    id: 103,
    '': 1,
    name: 'Kia Ray',
    type: 'TRANSPORT',
    description: null,
    address: '',
    estimated_hours: 1,
    cost: 28089,
    rank: 0,
  },
];
